apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-sky-blog-1
spec:
  displayName: Sky Blog Theme
  author:
    name: sky
    website: https://github.com/sky121666
  description: 基于Vite、Tailwind CSS、DaisyUI和Alpine.js的现代化Halo主题
  logo: /themes/theme-sky-blog-1/assets/images/heihei.png
  homepage: https://www.halo.run/store/apps/app-squauk4h
  repo: https://github.com/sky121666/halo-theme-sky-blog-1
  issues: https://github.com/sky121666/halo-theme-sky-blog-1/issues
  settingName: "theme-sky-blog-1-setting"
  configMapName: "theme-sky-blog-1-configMap"
  version: "2.0.0"
  requires: ">=2.22.9"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/sky121666/halo-theme-sky-blog-1/blob/main/LICENSE"
  customTemplates:
    page:
      - name: 关于
        description: 展示个人/站点信息，集成 GitHub、技术栈、评论等
        file: page_about.html
    category:
      - name: 强制卡片风格
        description: 忽略全局设置，此分类强制使用卡片风格
        file: category-card.html
      - name: 强制列表风格
        description: 忽略全局设置，此分类强制使用列表风格
        file: category-list.html
      - name: 强制杂志风格
        description: 忽略全局设置，此分类强制使用杂志风格
        file: category-magazine.html
      - name: 强制极简风格
        description: 忽略全局设置，此分类强制使用极简风格
        file: category-minimal.html
